### ISSUE TITLE
Export morph, Select Morphs saved preset does not work

### ISSUE THREAD

**Issue by WolfExplode** [daz3d/DazToBlender#159] opened 2023-01-08 16:42 UTC
Export Morphs > choose morphs > choose preset > Mymorphs.csv
does not fill in morphs to export

there is nothing wrong with the csv file, none of my csv files work

**Comment by danielbui78** [comment] 2023-02-12 16:33
Sorry for the late response.  I am unable to reproduce the error you described.  Please note that morph selection presets will only appear in the "Morphs to Export" section if the morph is compatible with the currently selected Figure.  If you are still having problems, please post the CSV file along with the version number of the Blender Bridge that you are using.

**Comment by danielbui78** [comment] 2023-07-03 16:43
I will close this issue since there have been no further responses or questions.  Please feel free to open a new issue in the future.

Regards

**Closed by danielbui78** 2023-07-03 16:43 UTC
Labels: question
