### ISSUE TITLE
Morphs List becomes empty after load existing .blend files

### ISSUE THREAD

**Issue by yhlai-code** [daz3d/DazToBlender#71] opened 2021-06-19 04:15 UTC
When I export from Daz and import in Blender, the Morph List works as expected. However, I saved the .blend file, closed Blender, re-open it and load the saved file, Morph List is all gone.

![image](https://user-images.githubusercontent.com/538696/122630617-ae051400-d0f7-11eb-903a-2e9fd9c849f9.png)

Blender version: 2.9.3
DazToBlender version: 2.3.7, 2.3.8, 2.3.9 all have this problem.

**Comment by yhlai-code** [comment] 2021-06-19 04:20
Weirdly, if I just load a new file, and then load the saved file again, this bug doesn't occur. It only occurs after I closing Blender and open it again.

**Comment by umbcel** [comment] 2021-06-24 20:27
I have the same problem.

**Comment by enversl** [comment] 2021-06-26 19:50
same problem. temporary solution: if you create new shape key with morph they will not dissapere 
![error](https://user-images.githubusercontent.com/85310936/123524105-bc8f9480-d6d0-11eb-9a41-e3dcd591d2a0.png)

**Comment by umbcel** [comment] 2021-06-27 11:30
> 
> 
> same problem. temporary solution: if you create new shape key with morph they will not dissapere
> ![error](https://user-images.githubusercontent.com/85310936/123524105-bc8f9480-d6d0-11eb-9a41-e3dcd591d2a0.png)

I created a new shape key but not work for me.
Please can you explain better the exact steps of this workaround?
The new shape key must be created before save the Blender document for the first time?

**Comment by enversl** [comment] 2021-06-28 18:08
![1](https://user-images.githubusercontent.com/85310936/123683252-ac082700-d854-11eb-9725-f882c6b2b50e.png)
![2](https://user-images.githubusercontent.com/85310936/123683254-ad395400-d854-11eb-90d7-c32d416d978e.png)
try like on screens.
create "new shape from mix"

**Comment by yhlai-code** [comment] 2021-07-04 03:06
https://github.com/daz3d/DazToBlender/pull/75/commits/a43a131cab0f96be21cfca5b34b1e705d5e1c2e5

For people who need morphs now, I made a simple patch. Note that it's a workaround, not a proper fix.

**Comment by chlbrn** [comment] 2021-07-09 07:29
Same here, and genesis 8 character's eyelashes don't follow the facial expressions on my end.
What I have to do is to join the eyelashes with body mesh and delete shape keys (facial expressions) with drivers like eCTRLAngry_HD since they don't work for now.
And use the shape keys with no drivers like head_eCTRLAngry_HD instead. Those expressions still work and if you make eyelashes join with body mesh, the eyelashes will follow since they have the same shape keys.

**Comment by Popinjayishuman** [comment] 2021-08-05 18:04
This has been fixed. If you are still seeing problems make sure to refresh by going to the Morphs List under the Daz To Blender plugin sidebar. From here, beside where it says 'choose character' click the refresh symbol and you should will be able to select the character from the dropdown.

**Comment by chlbrn** [comment] 2021-08-06 02:27
> This has been fixed. If you are still seeing problems make sure to refresh by going to the Morphs List under the Daz To Blender plugin sidebar. From here, beside where it says 'choose character' click the refresh symbol and you should will be able to select the character from the dropdown.

After refreshing, I can select character but the morph list is still missing, I am not sure why.

**Comment by samjay3d** [comment] 2021-08-07 20:58
I am going to reopen this, for now, @chlbrn can you share more information about what you exported and which version of blender are you using?

**Comment by chlbrn** [comment] 2021-08-08 01:20
> I am going to reopen this, for now, @chlbrn can you share more information about what you exported and which version of blender are you using?

Hi, I am currently using Blender 2.91 and 2.93 with Bridge 2.3.9. The character I exported is my own custom character based on genesis 8 female. I exported body mesh and some expressions (morphs) and no texture or material changed. I think the problem is that re-opening the .blend file does not reload the morph list no matter whether the Bridge recognize the character. I just did a quick test using genesis 8 female base model and the issue still persists.

**Comment by samjay3d** [comment] 2021-08-09 13:37
> > I am going to reopen this, for now, @chlbrn can you share more information about what you exported and which version of blender are you using?
> 
> Hi, I am currently using Blender 2.91 and 2.93 with Bridge 2.3.9. The character I exported is my own custom character based on genesis 8 female. I exported body mesh and some expressions (morphs) and no texture or material changed. I think the problem is that re-opening the .blend file does not reload the morph list no matter whether the Bridge recognize the character. I just did a quick test using genesis 8 female base model and the issue still persists.

Could you share your blend file? Also to make sure the version should be 2.4.0 looks like i forgot to get the release together. 

https://github.com/daz3d/DazToBlender/releases/tag/2.4.0

Maybe check if this solves your issue?

**Comment by chlbrn** [comment] 2021-08-09 14:27
> Could you share your blend file? Also to make sure the version should be 2.4.0 looks like i forgot to get the release together.
> 
> https://github.com/daz3d/DazToBlender/releases/tag/2.4.0
> 
> Maybe check if this solves your issue?
Thank you Sam, 2.4.0 fixed the problem, the refresh button now works like a charm!

**Comment by samjay3d** [comment] 2021-08-09 15:46
Awesome closing this now!

**Closed by samjay3d** 2021-08-09 15:46 UTC

**Comment by rheesbirman** [comment] 2023-10-28 23:44
Hi, this issue is still happening (or has come back) in 2023 v1.1 and blender v3.3. The morph list vanishes after saving the .blend file, closing blender, and reopening the file.
